"""Added oreol column in Article

Revision ID: 4958344606a8
Revises: f3d641c2b257
Create Date: 2024-06-15 22:19:13.088055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4958344606a8'
down_revision = 'f3d641c2b257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oreol', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('oreol')

    # ### end Alembic commands ###
